server:
  port: 8086

spring:
  application:
    name: SEARCH-SERVICE
  config:
    import: optional:configserver:http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Service URLs
post-service:
  url: http://localhost:8085

# Search Configuration
search:
  max-results: 100
  highlight-enabled: true
  fuzzy-search-enabled: true