server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogbaaz_userservice
    username: postgres
    password: postgre
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8083
#  profile:
#    active: dev


